#!/bin/sh

# Set the default cursor for the xsession
xsetroot -cursor_name left_ptr &

# Recover wallpaper set with feh if exists
if [[ -f "$HOME/.fehbg" ]]; then
	~/.fehbg 
fi

# Lauch dwmblocks
dwmblocks &

# Launch compositor for transparency
picom &

# Launch dunst as default notification deamon
dunst & 

# Disable sound bell
xset -b &

# Enable lockscreen
xss-lock -l -- multilockscreen --lock dim &
