- defaults:
    link:
      relink: true
      create: true

- clean: ['~', '~/.config']

- link:
    ~/.config/xmonad: xmonad
    ~/.config/dunst: dunst
    ~/.config/bottom: bottom
    ~/.config/gh: gh
    ~/.config/git: git
    ~/.config/nvim: nvim
    ~/.config/paru: paru
    ~/.config/picom: picom
    ~/.config/rofi: rofi
    ~/.config/gtk-3.0: theme/gtk
    ~/.icons: theme/icons
    ~/.gtkrc-2.0: theme/gtk/gtk-2
    ~/.zshrc: zsh/.zshrc
