- defaults:
    link:
      relink: true
      create: true

- clean: ['~', '~/.config']

- link:
    ~/.config/xmonad: xmonad
    ~/.config/polybar: polybar
    ~/.config/dunst: dunst
    ~/.config/bottom: bottom
    ~/.config/gh: gh
    ~/.config/git: git
    ~/.config/nvim: nvim
    ~/.config/paru: paru
    ~/.config/picom: picom
    ~/.config/rofi: rofi
    ~/.config/fish: fish
    ~/.config/gtk-3.0: theme/gtk
    ~/.local/share/fonts: fonts
    ~/.icons: theme/icons
    ~/.gtkrc-2.0: theme/gtk/gtk-2
    ~/.bashrc: bash/bashrc
    ~/.profile: profile/profile
    ~/.xsession: xorg/xsession
    ~/.tmux.conf: tmux/tmux.conf

- shell:
  - [fish ~/.config/fish/init.fish, Setting up fish]
