- defaults:
    link:
      relink: true
      create: true

- clean: ['~', '~/.config']

- link:
    ~/.config/dunst: dunst
    ~/.config/bottom: bottom
    ~/.config/gh: gh
    ~/.config/git: git
    ~/.config/nvim: nvim
    ~/.config/paru: paru
    ~/.config/systemd: systemd
    ~/.config/alacritty: alacritty
    ~/.config/dwm: dwm
    ~/.config/dwmblocks: dwmblocks
    ~/.config/picom: picom
    ~/.config/rofi: rofi
    ~/.config/fish: fish
    ~/.config/bat: bat
    ~/.config/gtk-3.0: theme/gtk
    ~/.config/tmux: tmux
    ~/.local/share/fonts: fonts
    ~/.local/bin: bin
    ~/.icons: theme/icons
    ~/.gtkrc-2.0: theme/gtk/gtk-2
    ~/.bashrc: bash/bashrc
    ~/.profile: profile/profile
    ~/.xsession: xorg/xsession

- shell:
  - [fish ~/.config/fish/init.fish, Setting up fish]
  -
    command: cd dwm && sudo make install clean
    stdin: true
    stdout: true
    stderr: true
    description: Installing dwm
    quiet: true
  -
    command: cd dwmblocks && sudo make install clean
    stdin: true
    stdout: true
    stderr: true
    description: Installing dwmblocks
    quiet: true
