- defaults:
    link:
      relink: true
      create: true

- clean: ['~', '~/.config']

- link:
    ~/.config/xmonad: xmonad
    ~/.config/dunst: dunst
    ~/.config/bottom: bottom
    ~/.config/gh: gh
    ~/.config/git: git
    ~/.zshrc: zsh/.zshrc
